name : HackPrinceton 2017
brand : HackPrinceton
description : HackPrinceton Landing Page
keyword : 
url : https://hackprinceton.com
email : team@hackprinceton.com
twitter : 
github : 
author : Casey Chow
year : 2017
markdown : kramdown
exclude :
  - node_modules
